### ISSUE TITLE
new casting syntax

### ISSUE THREAD

**Issue by SchokiCoder** [c2lang/documentation#11]
"language/builtin_functions.md" doesn't mention casting, neither does "introduction/changes_from_c.md".
Add sub-chapter to builtin_functions?

PS. I am suddenly going to open a few issues not with the intention to spam.
I just accumulated these in my own notes in the last few days and wanted them to be known before i am going AFK for ~2 weeks.
I have originally planned to take care of them myself.
So if nothing in here is too bad in your eyes, you can leave them for me.

**Comment by bvdberg** [comment]
I added a small section on casts
